name: Run LT Tunnel

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'LambdaTest Username'
        default: 'auteur-bot@ltqa.lambdatestautomation.com'
        required: true
      access_key:
        description: 'LambdaTest Access Key'
        required: true
      tunnel_name:
        description: 'Tunnel Name'
        required: true
      env:
        description: 'Environment (stage or prod)'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - stage

jobs:
  run-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log Trigger Info
        run: |
          echo "Workflow triggered by: ${{ github.actor }}"
          echo "LambdaTest Username: ${{ github.event.inputs.username }}"
          echo "Environment: ${{ github.event.inputs.env }}"
          echo "Tunnel Name: ${{ github.event.inputs.tunnel_name }}"

      - name: Make LT Binary Executable
        run: chmod +x ./LT
    

      - name: Run LT Tunnel
        run: |
          ./LT --user ${{ github.event.inputs.username }} \
               --key ${{ github.event.inputs.access_key }} \
               --env ${{ github.event.inputs.env }} -v --mitm \
               --tunnelName ${{ github.event.inputs.tunnel_name }}